server:
  port: 7002

eureka:
  instace:
    hostname: eureka7002.com  #eureka服务端的名称
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka/
    #单机版Eureka
     #defaultZone: http://localhost:7001/eureka/

